server:
  port: 9203

spring:
  application:
    name: cloud-oms
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    database: 15
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      druid:
        initial-size: 5
        min-idle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,slf4j
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/shop_cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: 12345678

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.cloud.**.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: "1"
      logic-not-delete-value: "0"
      id-type: assign_id

swagger:
  title: OMS模块接口文档
  license: Powered By cloud
  licenseUrl: https://cloud.vip
